# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-05 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='content',
            field=models.TextField(verbose_name='评论内容'),
        ),
    ]
