# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-02 02:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='电影分类')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='电影标题')),
                ('desc', models.CharField(default='现在没有电影简介', max_length=1024, verbose_name='电影简介')),
                ('release_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上映时间')),
                ('images', models.ImageField(null=True, upload_to='')),
                ('find', models.ManyToManyField(to='movie_details.Kind')),
            ],
        ),
    ]
