# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-02 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='featured分类')),
            ],
            options={
                'verbose_name': 'featured分类',
                'verbose_name_plural': 'featured分类',
            },
        ),
        migrations.AlterModelOptions(
            name='kind',
            options={'verbose_name': '电影分类', 'verbose_name_plural': '电影分类'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': '电影信息', 'verbose_name_plural': '电影信息'},
        ),
        migrations.AddField(
            model_name='movie',
            name='hotkind',
            field=models.ManyToManyField(to='movie_details.HotKind'),
        ),
    ]
