# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-06 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_details', '0002_auto_20181102_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='tail',
            field=models.FileField(null=True, upload_to='vedio'),
        ),
    ]
